import Head from 'next/head'
import Image from 'next/image'
import React from 'react'
import { Inter } from 'next/font/google'
import styles from './index.module.css'
import { Scene } from '../components/canvas/Scene'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
    return (
        <>
            <Head>
                <title>AR Test</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className={styles.home}>
                <Scene />
            </div>
        </>
    )
}
